---
# tasks file for roles/ansible-configure-node-exporter

- name: "Download node exporter"
  ansible.builtin.include_role:
    name: ansible-download-software
  vars:
    download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.{{ node_exporter_arch }}.tar.gz"
    file_name: node-exporter

- name: "Create User for node exporter"
  ansible.builtin.include_role:
    name: ansible-add-user
  vars:
    user_name: node-exporter
    group_name: node-exporter

- name: Copy systemd file
  ansible.builtin.copy:
    src: node-exporter.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'

- name: Just force systemd to re-execute itself (2.8 and above)
  ansible.builtin.systemd:
    daemon_reexec: true

- name: Enable and start node-exporter service
  ansible.builtin.systemd:
    state: started
    name: node-exporter
    enabled: true

- name: Open Port 9100 for node-exporter
  ufw:
    rule: allow
    port: 9100
    log: yes

